// <auto-generated />
using System;
using Dsg.Hrms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dsg.Hrms.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20260910183314_ErisimKaydi")]
    partial class ErisimKaydi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dsg.Hrms.Domain.Audit.AccessLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("access_type");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_access_log");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_access_log_trace_id");

                    b.HasIndex("AccessType", "OccurredAt")
                        .HasDatabaseName("ix_access_log_access_type_occurred_at")
                        .HasFilter("access_type IN ('Export', 'Report')");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_access_log_entity_name_entity_id");

                    b.HasIndex("UserAccountId", "OccurredAt")
                        .HasDatabaseName("ix_access_log_user_account_id_occurred_at");

                    b.ToTable("access_log", "audit");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Audit.ChangeLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_change_log");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_change_log_trace_id");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_change_log_entity_name_entity_id");

                    b.HasIndex("UserAccountId", "OccurredAt")
                        .HasDatabaseName("ix_change_log_user_account_id_occurred_at");

                    b.ToTable("change_log", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
