// <auto-generated />
using System;
using Dsg.Hrms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dsg.Hrms.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20260930142116_AccountInvitations")]
    partial class AccountInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dsg.Hrms.Domain.Audit.AccessLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("access_type");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_access_log");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_access_log_trace_id");

                    b.HasIndex("AccessType", "OccurredAt")
                        .HasDatabaseName("ix_access_log_access_type_occurred_at")
                        .HasFilter("access_type IN ('Export', 'Report')");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_access_log_entity_name_entity_id");

                    b.HasIndex("UserAccountId", "OccurredAt")
                        .HasDatabaseName("ix_access_log_user_account_id_occurred_at");

                    b.ToTable("access_log", "audit");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Audit.ChangeLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_change_log");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_change_log_trace_id");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_change_log_entity_name_entity_id");

                    b.HasIndex("UserAccountId", "OccurredAt")
                        .HasDatabaseName("ix_change_log_user_account_id_occurred_at");

                    b.ToTable("change_log", "audit");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.AccountInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_account_invitation");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_account_invitation_person_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_invitation_public_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_invitation_token_hash");

                    b.ToTable("account_invitation", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_account_invitation_reason", "btrim(reason) <> ''");

                            t.HasCheckConstraint("ck_account_invitation_token_hash_length", "length(token_hash) = 44");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.LoginChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<int>("OfferedChannels")
                        .HasColumnType("integer")
                        .HasColumnName("offered_channels");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.Property<Guid?>("VerificationCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_code_id");

                    b.HasKey("Id")
                        .HasName("pk_login_challenge");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_login_challenge_public_id");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_login_challenge_user_account_id");

                    b.ToTable("login_challenge", "identity");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.LoginThrottle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_login_throttle");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasDatabaseName("ix_login_throttle_email_hash");

                    b.ToTable("login_throttle", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_login_throttle_email_hash_length", "length(email_hash) = 44");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_token_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.ToTable("refresh_token", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_token_hash_length", "length(token_hash) = 44");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RegistrationAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DecoyCodeExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decoy_code_expires_at");

                    b.Property<int>("DecoyFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("decoy_failed_attempts");

                    b.Property<int>("DecoyMaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("decoy_max_attempts");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NationalIdHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_id_hash");

                    b.Property<int>("OfferedChannels")
                        .HasColumnType("integer")
                        .HasColumnName("offered_channels");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VerificationCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_code_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_registration_attempt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_registration_attempt_person_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_attempt_public_id");

                    b.HasIndex("IpAddress", "CreatedAt")
                        .HasDatabaseName("ix_registration_attempt_ip_address_created_at");

                    b.HasIndex("NationalIdHash", "CreatedAt")
                        .HasDatabaseName("ix_registration_attempt_national_id_hash_created_at");

                    b.ToTable("registration_attempt", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_registration_attempt_channels", "offered_channels BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_registration_attempt_national_id_hash_length", "length(national_id_hash) = 44");

                            t.HasCheckConstraint("ck_registration_attempt_purpose", "purpose IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RegistrationCodeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("NationalIdHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_id_hash");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.HasKey("Id")
                        .HasName("pk_registration_code_request");

                    b.HasIndex("NationalIdHash", "RequestedAt")
                        .HasDatabaseName("ix_registration_code_request_national_id_hash_requested_at");

                    b.ToTable("registration_code_request", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_registration_code_request_hash_length", "length(national_id_hash) = 44");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_public_id");

                    b.ToTable("role", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "system-administrator",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Sistem Yöneticisi",
                            PublicId = new Guid("0192a3b4-0001-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Code = "hr-identity-operations",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "İK Kimlik İşlemleri",
                            PublicId = new Guid("0192a3b4-0002-7000-8000-000000000002")
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RoleGrant", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.HasKey("RoleId", "Permission")
                        .HasName("pk_role_permission");

                    b.HasIndex("Permission")
                        .HasDatabaseName("ix_role_permission_permission");

                    b.ToTable("role_permission", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            Permission = "identity.account.view"
                        },
                        new
                        {
                            RoleId = 1L,
                            Permission = "identity.account.update"
                        },
                        new
                        {
                            RoleId = 1L,
                            Permission = "identity.invite.create"
                        },
                        new
                        {
                            RoleId = 1L,
                            Permission = "identity.sync.view"
                        },
                        new
                        {
                            RoleId = 1L,
                            Permission = "identity.sync.create"
                        },
                        new
                        {
                            RoleId = 1L,
                            Permission = "system.parameter.view"
                        },
                        new
                        {
                            RoleId = 1L,
                            Permission = "system.parameter.update"
                        },
                        new
                        {
                            RoleId = 2L,
                            Permission = "identity.account.view"
                        },
                        new
                        {
                            RoleId = 2L,
                            Permission = "identity.account.update"
                        },
                        new
                        {
                            RoleId = 2L,
                            Permission = "identity.invite.create"
                        },
                        new
                        {
                            RoleId = 2L,
                            Permission = "identity.sync.view"
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StatusNote")
                        .HasColumnType("text")
                        .HasColumnName("status_note");

                    b.Property<int?>("StatusReason")
                        .HasColumnType("integer")
                        .HasColumnName("status_reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_person_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_public_id");

                    b.ToTable("user_account", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_account_manual_note", "status_reason IS DISTINCT FROM 3 OR (status_note IS NOT NULL AND btrim(status_note) <> '')");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user_role");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_public_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserAccountId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_user_account_id_role_id");

                    b.ToTable("user_role", "identity");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivityWindowCount")
                        .HasColumnType("integer")
                        .HasColumnName("activity_window_count");

                    b.Property<DateTimeOffset>("ActivityWindowStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activity_window_started_at");

                    b.Property<int?>("EndReason")
                        .HasColumnType("integer")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_user_session");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_session_public_id");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_user_session_user_account_id")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("user_session", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_session_ended", "(ended_at IS NULL) = (end_reason IS NULL)");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.VerificationCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<int>("MaxFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_failed_attempts");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_verification_code");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_code_public_id");

                    b.HasIndex("PersonId", "CreatedAt")
                        .HasDatabaseName("ix_verification_code_person_id_created_at");

                    b.HasIndex("PersonId", "Purpose", "Status")
                        .HasDatabaseName("ix_verification_code_person_id_purpose_status");

                    b.ToTable("verification_code", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_verification_code_attempts", "failed_attempts >= 0 AND max_failed_attempts > 0");

                            t.HasCheckConstraint("ck_verification_code_hash_length", "length(code_hash) = 44");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Notifications.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("queued_at");

                    b.Property<string>("RecipientMasked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_masked");

                    b.Property<string>("ResultCode")
                        .HasColumnType("text")
                        .HasColumnName("result_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_delivery");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_public_id");

                    b.HasIndex("PersonId", "QueuedAt")
                        .HasDatabaseName("ix_delivery_person_id_queued_at");

                    b.HasIndex("Status", "QueuedAt")
                        .HasDatabaseName("ix_delivery_status_queued_at");

                    b.ToTable("delivery", "notification");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Organization.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<short>("LogoFirmNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("logo_firm_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasIndex("LogoFirmNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_company_logo_firm_number");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_public_id");

                    b.ToTable("company", "organization");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Employment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LogoRef")
                        .HasColumnType("integer")
                        .HasColumnName("logo_ref");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("RegistryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registry_code");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("termination_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_employment");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employment_company_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_employment_public_id");

                    b.HasIndex("RegistryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employment_registry_code");

                    b.HasIndex("PersonId", "IsActive")
                        .HasDatabaseName("ix_employment_person_id_is_active");

                    b.ToTable("employment", "personnel", t =>
                        {
                            t.HasCheckConstraint("ck_employment_termination_after_hire", "termination_date IS NULL OR termination_date >= hire_date");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsEmailShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_shared");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_person_email");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_national_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_public_id");

                    b.ToTable("person", "personnel", t =>
                        {
                            t.HasCheckConstraint("ck_person_email_lowercase", "email IS NULL OR email = lower(email)");

                            t.HasCheckConstraint("ck_person_mobile_phone_format", "mobile_phone IS NULL OR mobile_phone ~ '^5[0-9]{9}$'");

                            t.HasCheckConstraint("ck_person_national_id_format", "national_id ~ '^[1-9][0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Sync.PersonnelSyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountsDeactivated")
                        .HasColumnType("integer")
                        .HasColumnName("accounts_deactivated");

                    b.Property<int>("AccountsReactivated")
                        .HasColumnType("integer")
                        .HasColumnName("accounts_reactivated");

                    b.Property<int>("CompaniesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("companies_changed");

                    b.Property<int>("EmploymentsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("employments_created");

                    b.Property<int>("EmploymentsDeactivated")
                        .HasColumnType("integer")
                        .HasColumnName("employments_deactivated");

                    b.Property<int>("EmploymentsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("employments_updated");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<int>("PersonsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("persons_created");

                    b.Property<int>("PersonsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("persons_updated");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("integer")
                        .HasColumnName("records_read");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("records_skipped");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("Id")
                        .HasName("pk_sync_run");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_run_public_id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sync_run_started_at");

                    b.ToTable("sync_run", "personnel");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Sync.PersonnelSyncWarning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("RegistryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registry_code");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_sync_warning");

                    b.HasIndex("RunId", "RegistryCode")
                        .HasDatabaseName("ix_sync_warning_run_id_registry_code");

                    b.ToTable("sync_warning", "personnel");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Settings.SystemParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("ProtectedValue")
                        .HasColumnType("text")
                        .HasColumnName("protected_value");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_system_parameter");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_system_parameter_key");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_system_parameter_public_id");

                    b.ToTable("system_parameter", "settings", t =>
                        {
                            t.HasCheckConstraint("ck_system_parameter_key_format", "key ~ '^PRM-[A-Z]{3}-[0-9]{2}$'");

                            t.HasCheckConstraint("ck_system_parameter_single_value", "value IS NULL OR protected_value IS NULL");
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Infrastructure.Data.Configurations.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Code")
                        .HasName("pk_permission");

                    b.ToTable("permission", "identity");

                    b.HasData(
                        new
                        {
                            Code = "identity.account.view",
                            Description = "Hesap durumunu görme"
                        },
                        new
                        {
                            Code = "identity.account.update",
                            Description = "Hesabı pasife alma ve yeniden aktifleştirme"
                        },
                        new
                        {
                            Code = "identity.invite.create",
                            Description = "Parola oluşturma bağlantısı gönderme"
                        },
                        new
                        {
                            Code = "identity.sync.view",
                            Description = "Senkronizasyon durumunu görme"
                        },
                        new
                        {
                            Code = "identity.sync.create",
                            Description = "Senkronizasyonu elle başlatma"
                        },
                        new
                        {
                            Code = "system.parameter.view",
                            Description = "Sistem parametrelerini görme"
                        },
                        new
                        {
                            Code = "system.parameter.update",
                            Description = "Sistem parametrelerini değiştirme"
                        });
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.AccountInvitation", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Personnel.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_invitation_person_person_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.LoginChallenge", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_login_challenge_user_account_user_account_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Identity.UserSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_session_session_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RegistrationAttempt", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Personnel.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_registration_attempt_person_person_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.RoleGrant", b =>
                {
                    b.HasOne("Dsg.Hrms.Infrastructure.Data.Configurations.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("Permission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission");

                    b.HasOne("Dsg.Hrms.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.UserAccount", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Personnel.Person", null)
                        .WithOne()
                        .HasForeignKey("Dsg.Hrms.Domain.Identity.UserAccount", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_account_person_person_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("Dsg.Hrms.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_account_user_account_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_user_account_user_account_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Identity.VerificationCode", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Personnel.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verification_code_person_person_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Employment", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Organization.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employment_company_company_id");

                    b.HasOne("Dsg.Hrms.Domain.Personnel.Person", "Person")
                        .WithMany("Employments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employment_person_person_id");

                    b.Navigation("Company");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Sync.PersonnelSyncWarning", b =>
                {
                    b.HasOne("Dsg.Hrms.Domain.Personnel.Sync.PersonnelSyncRun", null)
                        .WithMany("Warnings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_warning_sync_run_run_id");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Person", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("Dsg.Hrms.Domain.Personnel.Sync.PersonnelSyncRun", b =>
                {
                    b.Navigation("Warnings");
                });
#pragma warning restore 612, 618
        }
    }
}
